### ISSUE TITLE
Failing to Compile

### ISSUE THREAD

**Issue by MineGrayTV** [sylae/DiegeticInfoDisplay#10] opened 2023-01-29 04:27 UTC
seems like there's an issue with MLFeed with the most recent update. The plugin was working great yesterday.

[Openplanet.log](https://github.com/sylae/DiegeticInfoDisplay/files/10528969/Openplanet.log)

**Comment by sylae** [comment] 2023-01-29 04:30
oh weird, thanks for the report! I'll look into this

**Comment by sylae** [comment] 2023-01-29 04:40
This looks like it's probably an issue with the MLFeed exports, tentatively I'm marking this as an upstream issue, but I might have to do some adjusting to work around it.

In the meantime, can you try reinstalling MLHook and MLFeed just to make sure they're valid (i see you're on the latest versions of both)?. Barring that, I'd say *maybe* check your JIT compiliation setting is off, but I'm not sure that would cause this.

**Comment by MineGrayTV** [comment] 2023-01-29 04:43
Fresh install of both, tried to enable DID again, script comp error

[Openplanet.log](https://github.com/sylae/DiegeticInfoDisplay/files/10528993/Openplanet.log)

**Comment by XertroV** [comment] 2023-01-29 04:45
@MineGrayTV I'm the dev of MLHook.

Looking at that second log you provided, I see
```
[    ScriptEngine] [17:42:24] [PluginManager]  Loaded zipped plugin 'DID' (version 0.2)
[   ScriptRuntime] [17:42:24] [PluginManager]  Reloading dependent plugin 'DID'
[    ScriptEngine] [17:42:24] [PluginManager]  Plugin 'DID' is already unloaded!
```
Which looks like something is going wrong there. 

If you want to run a test quickly -- can you install 'Buffer Time'. It's a plugin that provides an different kind of timer to CP splits. 
Then, open any map you've finished before, and you should see a new timer at the bottom of the screen. If you do, that means MLFeed is working.

**Comment by XertroV** [comment] 2023-01-29 04:49
Oh also, @MineGrayTV Do you have MLFeed disabled by any chance?

@sylae I think you need to wrap these in preprocessor statements: https://github.com/sylae/DiegeticInfoDisplay/blob/3819b25b592201c437cfbf5129e5727b38f79e01/DID.as#L145-L146. Alternatively, you can define types with these names in DIDAddonsMLFeed.as (in an `#else` branch)

**Comment by sylae** [comment] 2023-01-29 04:52
That code doesn't exist on the current version, everything that uses MLFeed is siphoned off to https://github.com/sylae/DiegeticInfoDisplay/blob/main/DIDAddonsMLFeed.as with a small stub to load it here:

https://github.com/sylae/DiegeticInfoDisplay/blob/48469e3abdafd9147799084e481f0c7d21e1d613/DID.as#L126-L133

**Comment by XertroV** [comment] 2023-01-29 07:43
@MineGrayTV Can you try downloading the prior versions of MLHook and MLFeed and see if that fixes the issue? DID should still work.

That is: 

* 0.3.3 from https://openplanet.dev/plugin/mlhook/versions
* 0.4.4 from https://openplanet.dev/plugin/mlfeedracedata/versions

Put those `.op` files in `c:\users\<your user>\OpenplanetNext\Plugins` (or the equivalent directory). You can open the OpenplanetNext directory quickly from here: 
![image](https://user-images.githubusercontent.com/1046448/215312552-aedc9251-c096-44e0-8023-0c8037ea294e.png)

This will help us figure out if it's the new DID version or MLHook/MLFeed.

**Comment by MineGrayTV** [comment] 2023-01-29 07:44
@XertroV 
> If you want to run a test quickly -- can you install 'Buffer Time'. It's a plugin that provides an different kind of timer to CP splits. Then, open any map you've finished before, and you should see a new timer at the bottom of the screen. If you do, that means MLFeed is working.

>Can you try downloading the prior versions of MLHook and MLFeed and see if that fixes the issue? DID should still work.

I'll try those now

**Comment by MineGrayTV** [comment] 2023-01-29 07:53
8:50pm NZDT Buffer time works, and looks to be a great addition to my layout. DID does not work at this point
[Openplanet.log](https://github.com/sylae/DiegeticInfoDisplay/files/10529293/Openplanet.log)

8:52pm NZDT Both buffer time and DID don't work on prev versions as mentioned above, even with manual reload.
[Openplanet.log](https://github.com/sylae/DiegeticInfoDisplay/files/10529294/Openplanet.log)

**Comment by MineGrayTV** [comment] 2023-01-29 07:55
after updating the ML plugins through the in-game menu, DID can't compile 3 seperate times (as told to me by floats
[Openplanet.log](https://github.com/sylae/DiegeticInfoDisplay/files/10529299/Openplanet.log)
)

**Comment by XertroV** [comment] 2023-01-29 08:12
> 8:50pm NZDT Buffer time works, and looks to be a great addition to my layout. DID does not work at this point

Ahh I'm glad to hear :)

> 8:52pm NZDT Both buffer time and DID don't work on prev versions as mentioned above, even with manual reload.

The latest version of Buffer Time needs the latest version of MLFeed (though you can download a past version if you want -- I don't think that's necessary at this point, though).

> after updating the ML plugins through the in-game menu, DID can't compile 3 seperate times (as told to me by floats

Okay, thanks for all that testing. It seems like there's mb an issue with DID. Not exactly sure what, yet, though (and could be a red herring if there's actually an openplanet bug or something). 

Just to check: you only have one copy of DID installed, right? Like you don't have a dev version, or a second `did.op` file or anything like that?

**Comment by XertroV** [comment] 2023-01-29 08:47
@sylae We are both using the edge version of openplanet right? Maybe that has something to do with it.

@MineGrayTV If you want to try running the edge version, you can download it here: https://openplanet.dev/download/next?branch=edge (or change your branch in openplanet settings, and check for updates). It's more locked down than the current version, and there are some other substantial under-the-hood changes. To change back, you can download and install the current version.

**Comment by MineGrayTV** [comment] 2023-01-29 09:42
@XertroV 

> Just to check: you only have one copy of DID installed, right? Like you don't have a dev version, or a second did.op file or anything like that?

Yes, there's only one version of DID.op installed

> If you want to try running the edge version...

I'm not running the edge version atm, and I can try that later on today, but I don't think that's a part of the issue at hand.

**Comment by sylae** [comment] 2023-01-29 09:49
oh fuck

Yeah it's not a fix for the MLHook export.as issue (i think) but DID definitely won't work on not-edge versions. `vec3::yz()` doesn't exist on main i guess? fuck, i'm gonna hotfix that at least

**Comment by sylae** [comment] 2023-01-29 09:57
Just pushed 0.2.1 to the approval queue, which should solve the missing swizzle at least. In the meantime @MineGrayTV if you have Club Access, could you try replacing your DID.op with [this](https://cdn.discordapp.com/attachments/356885321071198208/1069194409100464138/DID.op) and running it in dev mode? I don't know why this didn't show up in the earlier logs but that should at least get the main bit compiling

**Comment by sylae** [comment] 2023-01-29 10:03
Looking at the most recent log file, I definitely think there's something fucky with Openplanet going on here. v0.2 should have been giving these errors the entire time:

```
[    ScriptEngine] [20:54:02] [DID]  Glyph.as (20, 5) : INFO : Compiling void drawGlyph(vec3[], const vec2&in, float)
[    ScriptEngine] [20:54:02] [DID]  Glyph.as (43, 37) :  ERR : 'yz' is not a member of 'vec3'
[    ScriptEngine] [20:54:02] [DID]  Glyph.as (46, 37) :  ERR : 'yz' is not a member of 'vec3'
[    ScriptEngine] [20:54:02] [DID]  Glyph.as (49, 63) :  ERR : 'yz' is not a member of 'vec3'
[    ScriptEngine] [20:54:02] [PluginManager]  Script compilation failed!
```

but it's only showed up just now. I'm wondering if Openplanet is, like, caching plugin code or something? I don't get it.

**Comment by MineGrayTV** [comment] 2023-01-29 10:06
> Just pushed 0.2.1 to the approval queue, which should solve the missing swizzle at least. In the meantime @MineGrayTV if you have Club Access, could you try replacing your DID.op with [this](https://cdn.discordapp.com/attachments/356885321071198208/1069194409100464138/DID.op) and running it in dev mode? I don't know why this didn't show up in the earlier logs but that should at least get the main bit compiling

Sadly don't have Club access, I only have standard.

**Comment by sylae** [comment] 2023-01-29 10:08
> Sadly don't have Club access, I only have standard.

All good! Once it gets signed and published we should be able to test it then. Sorry for the bother with all this!

**Comment by MineGrayTV** [comment] 2023-01-29 10:12
Honestly, @sylae, I'm just trying to be helpful :D

**Comment by sylae** [comment] 2023-02-01 04:01
@MineGrayTV if you're available, the new version (v0.2.1) just got released on openplanet, would you mind checking if this still happens with that version?

**Comment by hypernucle** [comment] 2023-02-03 08:19
I've installed OpenPlanet and your plugin (plus MLFeed and MLHook), and on the game startup I'm getting these errors

[log.txt](https://github.com/sylae/DiegeticInfoDisplay/files/10576955/log.txt)

**Comment by sylae** [comment] 2023-02-03 10:35
Alright I'm gonna have to do more digging on this for sure. Right now no idea what's causing it because the compiler should see those exports just fine?

**Comment by XertroV** [comment] 2023-02-03 22:41
I can apparently replicate this now (not on my main PC). Will dig into it a bit.

![image](https://user-images.githubusercontent.com/1046448/216724792-5f3b3bb3-c5e2-43c2-bd69-2b7692444a4d.png)

**Comment by sylae** [comment] 2023-02-03 23:01
this was caused by an openplanet bug which is getting patched by Miss, in the meantime i'm gonna throw a hotfix down to work around it

openplanet discord ref: https://canary.discord.com/channels/276076890714800129/424967293538402334/1071096266760667196

**Closed as completed** 2023-02-03 23:01 UTC
Labels: bug, upstream blocked

**Comment by MineGrayTV** [comment] 2023-02-04 14:43
It works now. Everything works as expected.

**Comment by MineGrayTV** [comment] 2023-02-04 14:43
It works now. Everything works as expected.
